applicationName: voting

deployment:
  image:
    repository: ghcr.io/m4s-b3n/dotnet-sample
    tag: 1.0.0
    pullPolicy: Always
  ports:
    - name: http
      containerPort: 8080
  podLabels:
    orleans/serviceId: voting
    orleans/clusterId: voting
  containerSecurityContext:
    readOnlyRootFilesystem: false
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000

service:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http

ingress:
  enabled: true
  ingressClassName: nginx
  hosts:
    - host: localhost
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: voting
              port:
                number: 80
