name: Deploy Release

on:
  release:
    types: [released]
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      tag:
        type: string
        description: "Image tag to deploy (e.g. 1.0.0)"
        required: false
      latest:
        type: boolean
        description: "Tag image as latest"
        required: false
        default: false

permissions: {}

jobs:
  deploy:
    name: Deploy
    uses: infinite-automations/workflows/.github/workflows/cd-docker-helm.yml@ab1919f28d362159cbe6bb954ee2adca6c82b7fd # v1.0.0
    with:
      dry-run: ${{ github.event_name == 'pull_request' }}
      deploy-dry-run: ${{ vars.DRY_RUN_DEPLOY == 'true' }}
      tags: ${{ github.event_name == 'pull_request' && 'dry-run' || github.event.inputs.tag || github.event.release.tag_name }}
      release-name: voting
      chart: stakater/application
      chart-version: "5.2.3"
      namespace: voting
      helm-repos: |
        stakater=https://stakater.github.io/stakater-charts
      values-files: |
        helm/common.yaml
      set-values: |
        ingress.hosts[0].host=${{ vars.FQDN }}
        ${{ github.event.inputs.tag && format('deployment.image.tag={0}', github.event.inputs.tag) || '' }}
      deploy-environment: ${{ github.event_name == 'pull_request' && 'dry-run' || 'k8s-deploy' }}
      deploy-runner: ${{ github.event_name == 'pull_request' && 'ubuntu-latest' || 'k8s-deploy' }}
    secrets:
      KUBECONFIG: ${{ secrets.KUBECONFIG }}
    permissions:
      contents: read
      packages: write
