name: Release Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  ci:
    name: CI
    uses: infinite-automations/workflows/.github/workflows/ci-dotnet.yml@ab1919f28d362159cbe6bb954ee2adca6c82b7fd # v1.0.0
    with:
      dry-run: ${{ github.event_name == 'pull_request' }}
      dotnet-version: "10.x"
      working-directory: src
      docker-context: .
      docker-target: ci
      semrel-extra-plugins: |
        semantic-release-replace-plugin
    secrets:
      APP_ID: ${{ vars.APP_ID_SEMREL }}
      APP_PRIVATE_KEY: ${{ secrets.APP_KEY_SEMREL }}
    permissions:
      actions: read
      checks: write
      contents: write
      issues: write
      packages: write
      pull-requests: write
      statuses: write
